"""Shared project-wide constants."""

from http.client import BAD_REQUEST, GONE, METHOD_NOT_ALLOWED, NOT_FOUND

MAX_QUERY_LEN_FOR_FS_MAPPING = 8000

DEFAULT_IGNORED_HTTP_ERROR_STATUS_CODES = (BAD_REQUEST, NOT_FOUND, METHOD_NOT_ALLOWED, GONE)
